### ISSUE TITLE
Add Python 3.5 support (concerns also default installation method via Anaconda)

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2#653]
I have trouble using Brian2 with Python 3.5 (which one occurs when taking the default way of installing Brian 2 for Python 3 according to http://brian2.readthedocs.org/en/latest/introduction/install.html):

When installing recent Anaconda either Python version 2.7 or 3.5 can be chosen. For the first conda install brian2 works nicely. For the latter brian2 seems to require Python 3.4 and the dependency resolution fails. 

When installing Brian 2 manually (on Arch Linux) using Python 3.5 and "pip install Brian2" the installation runs through, however, when importing brian2 errors show up which differ for 2.0beta4 and recent master branch:

recent master:
```
$ python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import brian2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/augustin/Projects/Brian2/github/brian-team_brian2/brian2/__init__.py", line 64, in <module>
    import brian2.numpy_ as numpy
  File "/home/augustin/Projects/Brian2/github/brian-team_brian2/brian2/numpy_.py", line 8, in <module>
    from brian2.units.unitsafefunctions import *
  File "/home/augustin/Projects/Brian2/github/brian-team_brian2/brian2/units/__init__.py", line 4, in <module>
    from .allunits import (
  File "/home/augustin/Projects/Brian2/github/brian-team_brian2/brian2/units/allunits.py", line 2036, in <module>
    metre = Unit.create(get_or_create_dimension(m=1), "metre", "m")
  File "/home/augustin/Projects/Brian2/github/brian-team_brian2/brian2/units/fundamentalunits.py", line 1868, in create
    for s, i in itertools.izip(scale, dim._dims):
AttributeError: module 'itertools' has no attribute 'izip'
```

2.0beta4:
```
$ python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import brian2
ERROR    brian2: Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_f8y9cx8l.log  Thanks!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/__init__.py", line 66, in <module>
    from brian2.only import *
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/only.py", line 34, in <module>
    from brian2.stateupdaters import *
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/stateupdaters/__init__.py", line 7, in <module>
    from .explicit import *
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/stateupdaters/explicit.py", line 659, in <module>
    stochastic='additive')
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/stateupdaters/explicit.py", line 243, in __init__
    expression = str_to_sympy(element.expression)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/sympytools.py", line 51, in str_to_sympy
    rendered = SympyNodeRenderer().render_expr(expr)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 53, in render_expr
    return self.render_node(node.body)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 66, in render_node
    return getattr(self, methname)(node)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 122, in render_BinOp
    return self.render_BinOp_parentheses(node.left, node.right, node.op)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 117, in render_BinOp_parentheses
    return '%s %s %s' % (self.render_element_parentheses(left),
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 109, in render_element_parentheses
    return '(%s)' % self.render_node(node)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 66, in render_node
    return getattr(self, methname)(node)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 122, in render_BinOp
    return self.render_BinOp_parentheses(node.left, node.right, node.op)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 119, in render_BinOp_parentheses
    self.render_element_parentheses(right))
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 109, in render_element_parentheses
    return '(%s)' % self.render_node(node)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 66, in render_node
    return getattr(self, methname)(node)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 122, in render_BinOp
    return self.render_BinOp_parentheses(node.left, node.right, node.op)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 119, in render_BinOp_parentheses
    self.render_element_parentheses(right))
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 107, in render_element_parentheses
    return self.render_node(node)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 66, in render_node
    return getattr(self, methname)(node)
  File "/home/augustin/.local/lib/python3.5/site-packages/brian2/parsing/rendering.py", line 83, in render_Call
    elif node.starargs is not None:
AttributeError: 'Call' object has no attribute 'starargs'
```

**Comment by mstimberg** [comment]
The 2.0b4 does indeed not work with Python 3.5 (it was released before 3.5), but the current master branch does (the test suite is running against Python 3.5). From your error, it seems that you are trying to run Brian 2 directly from the source directory. This works for Python 2 but not for Python 3, because you'll have to use the files converted by the `2to3` utility. You'll therefore have to run `python setup.py install` or `pip install .` before using it. From the docs:

> You can also directly clone the git repository at github (https://github.com/brian-team/brian2) and then run `python setup.py install` or `python setup.py develop` or simply add the source directory to your PYTHONPATH (this will only work for Python 2.x).

**Comment by moritzaugustin** [comment]
Thank you for the clarification w.r.t. the source dir in PYTHONPATH not working in Python 3 mode!

I can confirm that Brian 2 recent master works with Python 3.5.

But wow do you proceed practically for developing using Python 3? Do a `pip install --user .` each time the files have changed? Or develop in Python 2 and run only tests in Python 3?

**Comment by mstimberg** [comment]
> Or develop in Python 2 and run only tests in Python 3?

Yes, at the moment this is how we work. The code is Python 2, and during the installation on a Python 3 system the code is converted. In the long run, we might switch to a code base that is both Python 2 and 3 compatible, but this will require us to be more careful during development (functions like `xrange` have to be imported from a compatibility package like `six`).
